config/routes.rb
Rails.application.routes.draw do
  resources :audiences do
    resources :areas
  end

  resources :areas, :only => ["show", "index"] do
    resources :audiences, :only => "show" do
      resources :notices
      resources :fund_verticals
    end
  end

  root 'areas#index'
  get 'blog' => 'pages#blog'

  get 'styleguide' => 'pages#styleguide'

end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  live       :boolean          default(FALSE)
#

class Area < ActiveRecord::Base
  has_and_belongs_to_many :audiences
  has_many :populations
  has_many :fund_verticals

  validates :name, presence: true, uniqueness: true

  def total_population_percent_by_gender(gender)
    (total_population_by_gender(gender).to_f / total_population) * 100
  end

  def total_population_by_gender(gender)
    populations.current_year.with_gender(gender).sum(:count)
  end

  def total_population
    populations.current_year.sum(:count)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    @areas = Area.all
  end

  def show
    @area = Area.find(params[:id])
    @home_stats = CareHomeAreaFacade.new(@area)
    @horizon_year = Date.current.year + 5
  end

end

app/helpers/areas_helper.rb
module AreasHelper
  # Helper to determine the gender percentage of an area
  def gender_percentage(area, gender)
    return "#{((Float( gender ) / area.total_population) * 100).round}%"
  end
end

app/views/areas/_care_homes_stats.html.haml
.clear
%header.aside-header.wider.care-home-stats
  %h1 Availability
  %aside
    .highlighted
      %h4 Total
    %div
      %span= pluralize(home_stats.total_homes, "home")
    %div
      %span= pluralize(home_stats.beds_count, "bed")
    %div
      %span= pluralize(home_stats.vacancies_count, "vacancy")
    %span.clear

.row.care-homes-stats

  %section.card
    %header
      %h4 Nursing
    .card-stat
      %h5 Beds
      %span.stat-value=home_stats.nursing_homes_beds_count

  %section.card
    %header
      %h4 Care
    .card-stat
      %h5 Beds
      %span.stat-value=home_stats.care_homes_beds_count

  %section.card
    %header
      %h4 Dementia
    .card-stat
      %h5 Homes
      %span.stat-value
        =home_stats.homes_with_dementia_care_count
    .card-stat
      %h5 Beds
      %span.stat-value
        =home_stats.homes_with_dementia_care_beds

  %section.card
    %header
      %h4 Only dementia patients
    .card-stat
      %h5 Homes
      %span.stat-value
        =home_stats.dementia_only_homes_count
    .card-stat
      %h5 Beds
      %span.stat-value
        =home_stats.dementia_only_homes_beds

app/views/areas/index.html.haml
%header.hero-header.subtle
  %h1 Open data – Open design
  %p Open data, open design process. Along with opening new datasets, we've released a number of tools and guides which we used during the project.


.row
  %section.third.home-summary
    = image_tag("ProjectBackground.jpg", alt: "Project background – Futuregov hackday")
    %h3 Background
    %article
      %p This collaborative project between FutureGov, Devon Council and Kingston and Sutton Councils was funded by the Cabinet Office with the aim to encourage councils to release more adult social care open data, publish it to data.gov.uk and to demonstrate the benefits of this approach.
  %section.third.home-summary
    = image_tag("ProjectFirstPhase.jpg", alt: 'The first phase - open data card game')
    %h3 The first phase
    %article
      %p Involved mapping existing data, identifying user needs and exploring what additional adult social care data could be released as open data regularly to data.gov.uk. Below you’ll find links to the data, design tools, a framework and guides for how the councils have released this data that you can reuse.
  %section.third.home-summary
    = image_tag("ProjectSecondPhase.jpg", alt: "The second phase - Building a prototype app using discovered data")
    %h3 The second phase
    %article
      %p Brings together relevant existing adult social care open data (including the data released in this project) into a prototype that demonstrates the benefits that releasing this data might have for council commissioners, providers and the general public.


/ %section.clear#home-introduction
/   %header.third
/     %h2 Local Care Market Demonstrator
/   .third
/     %p
/       %em Council’s have an important role to understand and shape their local adult social care market and they have to create a market positioning statement. It’s a full time job to pull together relevant data from different external sources and internal systems, analyse it and keep it up to date.
/     %p Our prototype attempts to demonstrate how bringing together open adult social care data can make it easier for councils to quickly understand their local care market and could help create new opportunities for providers and give more choice to users through greater transparency.
/   .third
/     = link_to image_path("wireframe_1_full.png"), class: 'quarter' do
/       = image_tag("wireframe_1.png", alt: 'Open Data prototype wireframe')
/     = link_to image_path("wireframe_2_full.png"), class: 'quarter' do
/       = image_tag("wireframe_2.png", alt: 'Open Data prototype wireframe')
/     = link_to image_path("mockup_1_full.png"), class: 'quarter' do
/       = image_tag("mockup_1.png", alt: 'Open Data prototype mockup')
/     = link_to image_path("mockup_2_full.png"), class: 'quarter' do
/       = image_tag("mockup_2.png", alt: 'Open Data prototype mockup')

/ .clear


- if @areas.any?
  %ul.link-list
    - @areas.each do |area|
      - if area.live?
        = link_to "View live prototype for #{area.name}", area_path(area), class: "button full"
  %br
%header.hero-header.subtle
  %h1 Design process and tools used

.row
  %section.home-progress.half.clear
    %header
      %h3 User personas to help understand data needs
    %article
      %p Working with council commissioners and data owners we created light user personas to help understand their needs and think about how using data differently might help. Download and reuse our personas or use our template to create your own.
      %ul.link-list
        %li= static_file('Personas', 'files/Open_Data_User-Cards.pdf')

  %section.home-progress.clear.half
    %header
      %h3 Open data co-design workshop materials
    %article
      %p Co-design workshops helped us to think about why certain data sets should be prioritised for release. Find out how we structured our workshops with providers and commissioners.
      %ul.link-list
        %li= static_file('Workshop materials', 'files/Open_Data_Workshop-Materials.pdf')

  %section.home-progress.half.clear
    %header
      %h3 A tool to explore how to combine data sets
    %article
      %p To help think about different ways data sets could be combined to meet user needs we created a card game. Download the game, edit and reuse it to help think about the value of data sets in different ways.
      %ul.link-list
        %li= static_file('Open data card game', 'files/Open_Data_Card-Game.pdf')

  %section.home-progress.clear.half
    %header
      %h3 Data sharing agreement templates
    %article
      %p We created a simple process for sharing data and project documentation. We’ve made use of collaborative tools like Google Drive to share data, making sure access rights were defined and setup at the beginning of the project.
      %ul.link-list
        %li= static_file('Data sharing agreements', 'files/Open_Data_Agreement-Template.docx')
  %section.home-progress.clear.half
    %header
      %h3 Final project report
    %article
      %p Our final report sets out in detail all of the work that we have done and more detail about the data sets that they are releasing.
      %ul.link-list
        %li= static_file('Final report', 'files/Open_Data_Final-Report.pdf')

  %section.home-progress.half.clear
    %header
      %h3 Open data framework
    %article
      %p Devon Council has created this short framework to accompany the final report that sets out the process they’ve followed and adapted to release open data. Our intention is that together with the final report, this provides a framework that can be followed by other councils allowing them to release more data.
      %ul.link-list
        %li= static_file('Open data framework', 'files/Open_Data_Publishing-Framework.pdf')

  %section.home-progress.half.clear
    %header
      %h3 Social Care open data project - blog post
    %article
      %p For the last few months we've been working on a very exciting project with Kingston Council, Sutton Council and FutureGov, aided by data scientist Edafe Onerhime. With all the hype around open data, we are still struggling to show practical applications and examples...
      %ul.link-list
        %li= link_to "Read the full blog post", blog_path


%br
%section.clear#area-list
  %header.third
    %h2
      We're live in Devon, with more areas coming soon
  .two_thirds

    - if @areas.any?
      %ul.link-list
        - @areas.each do |area|
          - if area.live?
            %li
              = link_to area.name, area_path(area)
              = link_to "View live prototype", area_path(area), class: "sub"
          - else
            %li
              = area.name
              %em
                data being prepared

%footer.hero-footer.subtle#home-subfooter
  %h3 Like to know more about the project?
  = mail_to "matt@wearefuturegov.com", "Get in touch", class: 'large-link'

app/views/areas/show.html.haml
%header.hero-header.subtle
  %h1 Inform your business decisions
  %p See population trends and understand spending patterns of Devon County Council



%header.aside-header
  %h1= "Population of " + @area.name
  %aside
    .highlighted
      %h4 Total Population
    %div
      %span
        = number_to_percentage(@area.total_population_percent_by_gender("female"), precision: 2)
        Female
      %br/
      %small
        = number_with_delimiter(@area.total_population_by_gender("female"))
        people
    %div
      %span
        = number_to_percentage(@area.total_population_percent_by_gender("male"), precision: 2)
        Male
      %br/
      %small
        = number_with_delimiter(@area.total_population_by_gender("male"))
        people
    %span.clear

%section.chart-wrapper.container
  %nav.super-tab-wrapper
    - @area.audiences.each_with_index do |audience, index|
      -# ID required by styling "#tab-1", "#tab-2" etc.
      -# Class to select default tab on view load
      -# '*_url' attributes are passed to area.coffee to load via AJAX
      .super-tab{ id: "tab-#{index + 1}",
                  class: (index == 0 ? "selected" : "unselected") + (audience.total_population_at(Date.current.year) == 0 ? " disabled" : ""),
                  data: { chart_url: area_audience_path(@area, audience),
                          details_url: area_audience_fund_verticals_path(@area, audience) } }
        %header.chart-header
          %h3= audience.title
        %article
          %p.notice
            %strong
              - if audience.total_population_at(Date.current.year) > 0
                #{number_with_delimiter(audience.total_population_at(Date.current.year))} People
              - else
                = I18n.t('data.missing')
          - if audience.total_population_at(Date.current.year) > 0
            .super-tab-trend.clear
              - audience.total_population_percent_change(Date.current.year, @horizon_year).tap do |change|
                - if change > 0
                  %i.icon.circle.circle-positive &#58776;
                - elsif change < 0
                  %i.icon.circle.circle-negative &#58777;
                %data
                  %span.stat-value
                    = number_to_percentage(change, precision: 2)
                  %p= change > 0 ? "Increase" : "Decrease"
            %p
              %strong
                = number_with_delimiter(audience.total_population_at(@horizon_year))
                predicted for #{@horizon_year}

    -# Only used on small screens
    %section.super-tab-info.clear

  %section.container#chart-container
    -# Rendered via AJAX (areas.coffee)
    %header.chart-header
      %h2.white
    .chart
    %h3 Legend
    %ul.legend

%h1.card-heading
  Public funding for care in
  = @area.name

%section.transparent.container#card-wrapper
  -# Will be rendered via AJAX (areas.coffee)


= render partial: "care_homes_stats", locals: { home_stats: @home_stats }


-# %footer.hero-footer.subtle
  %h3 Get the data